/** Nomes de BAPIs usados por Encomendas.cs. */
export const BAPI = {
  SALESORDER_CREATE: 'BAPI_SALESORDER_CREATEFROMDAT2',
  SALESORDER_SIMULATE: 'BAPI_SALESORDER_SIMULATE',
  SALESORDER_CHANGE: 'BAPI_SALESORDER_CHANGE',
  TRANSACTION_COMMIT: 'BAPI_TRANSACTION_COMMIT',
  TRANSACTION_ROLLBACK: 'BAPI_TRANSACTION_ROLLBACK',
} as const;
